package com.hedera.hcs.sxc.plugin.cryptography.keyrotation;
import com.hedera.hcs.sxc.interfaces.SxcKeyRotation;
/*-
 * ‌
 * hcs-sxc-java
 * ​
 * Copyright (C) 2019 - 2020 Hedera Hashgraph, LLC
 * ​
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ‍
 */

import java.security.InvalidAlgorithmParameterException;
import java.security.InvalidKeyException;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;

import java.security.NoSuchAlgorithmException;
import java.security.PublicKey;
import java.security.spec.InvalidKeySpecException;
import java.security.spec.X509EncodedKeySpec;


import javax.crypto.KeyAgreement;

import javax.crypto.interfaces.DHPublicKey;
import javax.crypto.spec.DHParameterSpec;
import org.apache.commons.lang3.tuple.Pair;

import lombok.extern.log4j.Log4j2;

@Log4j2
public class KeyRotation implements SxcKeyRotation{

    //private KeyAgreement aliceKeyAgree;
    
   
    public KeyRotation() {
    }

    /**
     * This is the initiator. Alice generates a public key for Bob and waits
     * for Bob's generated public key, obtained using
     * {@link #responder(byte[] alicesPublicKey)},  
     * so that she can  generate the shared key herself by 
     * executing {@link #finalize(byte[] bobsPublicKey, Keyagreement alicesKeyagree)} 
     * Alice needs to reuse the KeyAgreement when finalizing the exchange 
     * 
     * @return Alice's public key to send to responder and KeyAgreement to use for 
     * finalising.
     */
    
    @Override
    public Pair<KeyAgreement, byte[]> initiate() throws Exception {
       
        KeyAgreement aliceKeyAgree = null;
        byte[] alicePubKeyEnc  = null;    
        try {
            KeyPairGenerator aliceKpairGen = KeyPairGenerator.getInstance("DH");
            aliceKpairGen.initialize(2048);// 2048 if otherside not known
            KeyPair aliceKpair = aliceKpairGen.generateKeyPair();
            // keep the agreement in memory to reuse when bob sends his public key back to alice
            aliceKeyAgree = KeyAgreement.getInstance("DH");
            aliceKeyAgree.init(aliceKpair.getPrivate());
            // encode  public key and give it to Bob.
            alicePubKeyEnc = aliceKpair.getPublic().getEncoded();
        } catch (NoSuchAlgorithmException ex) {
            log.error(ex);
        }
        
        return Pair.of(aliceKeyAgree, alicePubKeyEnc);
    }

     /**
     * Uses initiators public key generated by {@link #initiate()} and obtains Bob's 
     * , the responder's, public key and shared secret. The public key is meant to be given to Alice
     * so that she can construct the same shared key herself. 
     * Note that this is a static method, Bob does not need to construct the object. 
     * 
     * @param initiatorPubKeyEnc
     * @return Pair.of(bob's public key, shared secret)
     */
    @Override
    public Pair<byte[], byte[]> respond(byte[] initiatorPubKeyEnc) throws Exception {
        byte[] bobPubKeyEnc = null;
        byte[] bobSecret  = null;
        try {
            KeyFactory bobKeyFac = KeyFactory.getInstance("DH");
            X509EncodedKeySpec x509KeySpec = new X509EncodedKeySpec(initiatorPubKeyEnc);
            PublicKey alicePubKey = bobKeyFac.generatePublic(x509KeySpec);
            // Bob gets the DH parameters associated with Alice's public key.
            DHParameterSpec dhParamFromAlicePubKey = ((DHPublicKey) alicePubKey).getParams();
            // Bob creates his own DH key pair
            KeyPairGenerator bobKpairGen = KeyPairGenerator.getInstance("DH");
            bobKpairGen.initialize(dhParamFromAlicePubKey);
            KeyPair bobKpair = bobKpairGen.generateKeyPair();
            // Bob creates and initializes his DH KeyAgreement object
            KeyAgreement bobKeyAgree = KeyAgreement.getInstance("DH");
            bobKeyAgree.init(bobKpair.getPrivate());
            bobPubKeyEnc = bobKpair.getPublic().getEncoded();
            bobKeyAgree.doPhase(alicePubKey, true);
            bobSecret = bobKeyAgree.generateSecret();
        } catch (NoSuchAlgorithmException | InvalidKeySpecException | InvalidAlgorithmParameterException | InvalidKeyException ex) {
            log.error(ex);
        }
        return Pair.of(bobPubKeyEnc, bobSecret);
    }

     /**
     * Use Bob's, the responder's, public key and the KeyAgreement that has been kept
     * after {@link #initiate() } to generate
     * a shared secret for Alice
     * 
     * @param responderPubKeyEnc This is responder's public key
     * @param keyAgreement Has been obtained during initialisation
     * @return the shared secret. 
     */
 
    
    @Override
    public byte[] finalise(byte[] responderPubKeyEnc, KeyAgreement keyAgreement) throws Exception {
        try {
            KeyFactory aliceKeyFac = KeyFactory.getInstance("DH");
            X509EncodedKeySpec x509KeySpec = new X509EncodedKeySpec(responderPubKeyEnc);
            PublicKey bobPubKey = aliceKeyFac.generatePublic(x509KeySpec);
            keyAgreement.doPhase(bobPubKey, true);
            
        } catch (InvalidKeySpecException | InvalidKeyException | IllegalStateException | NoSuchAlgorithmException ex) {
            log.error(ex);
        }
        return keyAgreement.generateSecret();
    }
    




 

  

    
    
 }
