version: '3.3'
services:
  Alice:
    container_name: Alice
    image: hederahashgraph/hcs-sxc-java-settlement-demo:latest
    restart: on-failure
    environment:
      APP_ID: "Alice"
      PUBKEY: 302a300506032b6570032100bcabbb31c4c6418ea323e02dd46c060f82936141b5d2d2a1da89e59e1267ab6b
      ROLES: "BUYER,SELLER"
      PAYMENT_ACCOUNT_DETAILS: "10-11-12 80640665"
      COLOR: 0a2c5a
    ports:
      - 8081:8081
    volumes:
      - ./:/config

  Bob:
    container_name: Bob
    image: hederahashgraph/hcs-sxc-java-settlement-demo:latest
    restart: on-failure
    environment:
      APP_ID: "Bob"
      PUBKEY: 302a300506032b6570032100bcabbb31c4c6418ea323e02dd46c060f82936141b5d2d2a1da89e59e1267ab6a
      ROLES: "BUYER,SELLER"
      PAYMENT_ACCOUNT_DETAILS: "13-01-32 79832564"
      COLOR: 0d431f
    ports:
      - 8082:8082
    volumes:
      - ./:/config

  Carlos:
   container_name: Carlos
   image: hederahashgraph/hcs-sxc-java-settlement-demo:latest
   restart: on-failure
   environment:
    APP_ID: "Carlos"
     PUBKEY: 302a300506032b6570032100bcabbb31c4c6418ea323e02dd46c060f82936141b5d2d2a1da89e59e1267ab6c
     ROLES: "BUYER,SELLER"
     PAYMENT_ACCOUNT_DETAILS: "22-11-14 70925098"
     COLOR: 275f4f
   ports:
     - 8083:8083
   volumes:
     - ./:/config

  Diana:
    container_name: Diana
    image: hederahashgraph/hcs-sxc-java-settlement-demo:latest
    restart: on-failure
    environment:
      APP_ID: "Diana"
      PUBKEY: 302a300506032b6570032100bcabbb31c4c6418ea323e02dd46c060f82936141b5d2d2a1da89e59e1267ab6d
      ROLES: "PAYCHANNEL"
      PAYMENT_ACCOUNT_DETAILS: "12-52-23 26789524"
      COLOR: 3f370b
    ports:
      - 8084:8084
    volumes:
      - ./:/config

  Erica:
   container_name: Erica
   image: hederahashgraph/hcs-sxc-java-settlement-demo:latest
   restart: on-failure
   environment:
     APP_ID: "Erica"
     PUBKEY: 302a300506032b6570032100bcabbb31c4c6418ea323e02dd46c060f82936141b5d2d2a1da89e59e1267ab6e
     ROLES: "BUYER,SELLER"
     PAYMENT_ACCOUNT_DETAILS: "09-34-21 46324354"
     COLOR: 49200e
   ports:
     - 8085:8085
   volumes:
     - ./:/config

  Farouk:
   container_name: Farouk
   image: hederahashgraph/hcs-sxc-java-settlement-demo:latest
   restart: on-failure
   environment:
     APP_ID: "Farouk"
     PUBKEY: 302a300506032b6570032100bcabbb31c4c6418ea323e02dd46c060f82936141b5d2d2a1da89e59e1267ab6f
     ROLES: "ARBITER,AUDITOR"
     PAYMENT_ACCOUNT_DETAILS: "10-69-43 86535765"
     COLOR: 2c0f4f
   ports:
     - 8086:8086
   volumes:
     - ./:/config

  Grace:
   container_name: Grace
   image: hederahashgraph/hcs-sxc-java-settlement-demo:latest
   restart: on-failure
   environment:
     APP_ID: "Grace"
     PUBKEY: 302a300506032b6570032100bcabbb31c4c6418ea323e02dd46c060f82936141b5d2d2a1da89e59e1267ab7a
     ROLES: "DEMO"
     PAYMENT_ACCOUNT_DETAILS: "10-32-52 55424452"
     COLOR: 4f0500
   ports:
     - 8087:8087
   volumes:
     - ./:/config

  Harry:
    container_name: Harry
    image: hederahashgraph/hcs-sxc-java-settlement-demo:latest
    restart: on-failure
    environment:
      APP_ID: "Harry"
      PUBKEY: 302a300506032b6570032100bcabbb31c4c6418ea323e02dd46c060f82936141b5d2d2a1da89e59e1267ab7b
      ROLES: "PAYCHANNEL"
      PAYMENT_ACCOUNT_DETAILS: "10-21-33 98321542"
      COLOR: 4d4c1f
    ports:
      - 8088:8088
    volumes:
      - ./:/config
