package com.hedera.hcs.sxc.interfaces;

import com.hedera.hcs.sxc.exceptions.KeyRotationException;
import javax.crypto.KeyAgreement;
import org.apache.commons.lang3.tuple.Pair;

public interface SxcKeyRotation {
    /**
     * 
     * @return Left: KeyAgreement to use, Right: PublicKeyEncoded
     * @throws KeyRotationException 
     */
    public Pair<KeyAgreement, byte[]> initiate() throws KeyRotationException;
    /**
     * 
     * @param initiatorPubKeyEnc Encoded key received from initiator
     * @return Left:  encoded  public key to send back to initiator, Right: PrivateKey for responder
     * @throws KeyRotationException 
     */
   
    public Pair<byte[],byte[]> respond(byte[] initiatorPubKeyEnc) throws KeyRotationException ;
    
    
    /**
     * 
     * @param responderPubKeyEnc Encoded public key received from responder
     * @param keyAgreement spec generated by initiator.  
     * @return
     * @throws KeyRotationException 
     */
    public byte[] finalise(byte[] responderPubKeyEnc, KeyAgreement keyAgreement ) throws KeyRotationException;
}
