# Connection details to the MQ component
queue:
  exchangeName: testExchange
  consumerTag: myConsumerTag
  producerTag: myProducerTag
  host: localhost
  port: 5672
  user: guest
  password: guest
  iterations: 10 # 0 for infinite
  delayMillis: 1000 # delay between each message